### ISSUE TITLE
Quick example timeout

### ISSUE THREAD

**Issue by kaktus42** [senecajs/seneca-mongo-store#58]
I just started up a mongodb and ran the quick example code with node.
The DB is running, accessible and empty.

What am I doing wrong?

```
Seneca Fatal Error
==================

Message: seneca: Action name:mongo-store,plugin:define,role:seneca,seq:2,tag:undefined failed: [TIMEOUT].

Code: act_execute

Details: { message: '[TIMEOUT]',
  pattern: 'name:mongo-store,plugin:define,role:seneca,seq:2,tag:undefined',
  fn: [Function: plugin_definition],
  cb: [Function: noop],
  instance: 'Seneca/9xs0slqk29ei/1475137197818/14391/3.2.1/-',
  'orig$': [Error: [TIMEOUT]],
  'message$': '[TIMEOUT]',
  plugin: {} }

Stack: 
    at Object.act_tm [as ontm] (/media/data/PROJECTS/Unity/gameServer/simple_server/game-server/node_modules/seneca/seneca.js:922:48)
    at timeout_check [as _repeat] (/media/data/PROJECTS/Unity/gameServer/simple_server/game-server/node_modules/seneca/node_modules/gate-executor/gate-executor.js:213:16)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

Instance: Seneca/9xs0slqk29ei/1475137197818/14391/3.2.1/-
  ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance, see senecajs.org/fatal.html)
    at Seneca.act_done (/media/data/PROJECTS/Unity/gameServer/simple_server/game-server/node_modules/seneca/seneca.js:1054:29)

When: 2016-09-29T08:20:20.483Z

Log: {kind:null,plugin:seneca,tag:3.2.1,id:9xs0slqk29ei/1475137197818/14391/3.2.1/-,code:act_execute,notice:seneca: 

[...]
```

**Comment by kaktus42** [comment]
just found the problem.
In the quick example the IP is 120.0.0.1
I misread it as 127.0.0.1
Changed IP, works.

Maybe you should make localhost as default.

**Comment by kaktus42** [comment]
Additionally this needs to have seneca-basic loaded to work

```
var seneca = require('seneca')()
seneca.use('mongo-store', {
  uri: 'mongodb://120.0.0.1:27017/dbname'
})
.use("basic")
.use("entity")

[...]
```

**Comment by SailajaG-123** [comment]
Seneca-mongo-store is not getting initialized properly. Getting below logs. Hence seneca server is not up and running.

{"kind":"plugin","case":"READY","name":"transport","level":300,"isot":"2023-12-10T09:43:36.551Z","when":1702201416551,"level_name":"info","seneca_id":"nrvm3ph0ob8i/1702201416354/22052/3.33.0/-","seneca_did":"kncw","plugin_name":"transport"}
{"kind":"fatal","level":600,"plugin":"seneca","tag":"3.33.0","id":"nrvm3ph0ob8i/1702201416354/22052/3.33.0/-","code":"plugin_define_failed","notice":"seneca: The definition action for the plugin mongo_store has failed: Cannot read properties of undefined (reading 'init') (    at Seneca.mongo_store (C:\\Learnings\\CNSCaseStudy\\Microservices\\node_modules\\seneca-mongo-store\\mongo-store.js:368:29). This error is considered fatal as all plugins have to initialize correctly. You should test the plugin by itself to verify that it is working correctly. Also ensure that the configuration options passed to the plugin are correct. These are shown below under in the DETAILS section. There could also be a bug in the plugin. If you think that is the case, please create a github issue on the plugin's repository, and include this error report.","err":{"eraro":true,"orig":{},"code":"plugin_define_failed","seneca":true,"package":"seneca","msg":"seneca: The definition action for the plugin mongo_store has failed: Cannot read properties of undefined (reading 'init') (    at Seneca.mongo_store (C:\\Learnings\\CNSCaseStudy\\Microservices\\node_modules\\seneca-mongo-store\\mongo-store.js:368:29). This error is considered fatal as all plugins have to initialize correctly. You should test the plugin by itself to verify that it is working correctly. Also ensure that the configuration options passed to the plugin are correct. These are shown below under in the DETAILS section. There could also be a bug in the plugin. If you think that is the case, please create a github issue on the plugin's repository, and include this error report.","details":{"fullname":"mongo_store","message":"Cannot read properties of undefined (reading 'init') (    at Seneca.mongo_store (C:\\Learnings\\CNSCaseStudy\\Microservices\\node_modules\\seneca-mongo-store\\mongo-store.js:368:29)","options":{"name":"cns_casestudy","host":"127.0.0.1","port":27017},"repo":"","errmsg":"Cannot read properties of undefined (reading 'init')","errline":"at Seneca.mongo_store (C:\\Learnings\\CNSCaseStudy\\Microservices\\node_modules\\seneca-mongo-store\\mongo-store.js:368:29)","orig$":{},"message$":"Cannot read properties of undefined (reading 'init')"},"callpoint":"at Seneca.mongo_store (C:\\Learnings\\CNSCaseStudy\\Microservices\\node_modules\\seneca-mongo-store\\mongo-store.js:368:29)","plugin":"mongo_store","plugin_callpoint":"at callpoint (C:\\Learnings\\CNSCaseStudy\\Microservices\\node_modules\\seneca\\lib\\common.js:412:36)","fatal$":true},"isot":"2023-12-10T09:43:36.556Z","when":1702201416556,"level_name":"fatal","seneca_id":"nrvm3ph0ob8i/1702201416354/22052/3.33.0/-"}
{"kind":"close","timeout":true,"level":600,"isot":"2023-12-10T09:43:47.673Z","when":1702201427673,"level_name":"fatal","seneca_id":"nrvm3ph0ob8i/1702201416354/22052/3.33.0/-"}
